// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IBSApplicationExercise1._generated
{
    [Table("Department")]
    [Index("DepartmentName", "AbbrDepartmentName", Name = "uqDepartmentNames", IsUnique = true)]
    public partial class Department
    {
        [Key]
        [Column("departmentID")]
        public Guid DepartmentId { get; set; }
        [Required]
        [Column("departmentName")]
        [StringLength(100)]
        [Unicode(false)]
        public string DepartmentName { get; set; }
        [Column("abbrDepartmentName")]
        [StringLength(50)]
        [Unicode(false)]
        public string AbbrDepartmentName { get; set; }
        [Column("createdBy")]
        [StringLength(100)]
        [Unicode(false)]
        public string CreatedBy { get; set; }
        [Column("createdDate", TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        [Column("modifiedBy")]
        [StringLength(100)]
        [Unicode(false)]
        public string ModifiedBy { get; set; }
        [Column("modifiedDate", TypeName = "datetime")]
        public DateTime ModifiedDate { get; set; }
    }
}