// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IBSApplicationExercise1._generated
{
    [Keyless]
    public partial class ReportingView
    {
        [Required]
        [Column("departmentName")]
        [StringLength(100)]
        [Unicode(false)]
        public string DepartmentName { get; set; }
        [Column("abbrDepartmentName")]
        [StringLength(50)]
        [Unicode(false)]
        public string AbbrDepartmentName { get; set; }
        [Column("email")]
        [StringLength(50)]
        [Unicode(false)]
        public string Email { get; set; }
        [Column("firstName")]
        [StringLength(50)]
        [Unicode(false)]
        public string FirstName { get; set; }
        [Column("lastName")]
        [StringLength(50)]
        [Unicode(false)]
        public string LastName { get; set; }
        [Column("active")]
        public bool? Active { get; set; }
        [Column("phoneNumber")]
        [StringLength(50)]
        [Unicode(false)]
        public string PhoneNumber { get; set; }
        [Column("startDate", TypeName = "datetime")]
        public DateTime? StartDate { get; set; }
        [Column("endDate", TypeName = "datetime")]
        public DateTime? EndDate { get; set; }
    }
}