// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IBSApplicationExercise1.Models
{
    [Table("DepartmentAssignment")]
    public partial class DepartmentAssignment
    {
        [Key]
        [Column("assignmentID")]
        public Guid AssignmentId { get; set; }
        [Column("personID")]
        public Guid PersonId { get; set; }
        [Column("departmentID")]
        public Guid DepartmentId { get; set; }
        [Column("departmentName")]
        [StringLength(100)]
        [Unicode(false)]
        public string DepartmentName { get; set; }
        [Required]
        [Column("email")]
        [StringLength(50)]
        [Unicode(false)]
        public string Email { get; set; }
        [Column("createdBy")]
        [StringLength(100)]
        [Unicode(false)]
        public string CreatedBy { get; set; }
        [Column("createdDate", TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        [Column("modifiedBy")]
        [StringLength(100)]
        [Unicode(false)]
        public string ModifiedBy { get; set; }
        [Column("modifiedDate", TypeName = "datetime")]
        public DateTime ModifiedDate { get; set; }

        [ForeignKey("PersonId")]
        [InverseProperty("DepartmentAssignments")]
        public virtual Person Person { get; set; }
    }
}